name: Build and Push Multiarch Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image and export to tar
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        outputs: type=docker,dest=/tmp/image.tar

    - name: Load image from tar
      run: |
        docker load -i /tmp/image.tar
        docker tag $(docker images --format "{{.Repository}}:{{.Tag}}" | head -n1) ghcr.io/crimsongabriel/zadanie1-app:latest

    - name: Push to GHCR manually
      run: docker push ghcr.io/crimsongabriel/zadanie1-app:latest

    - name: Scan image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/crimsongabriel/zadanie1-app:latest
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH
